apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingpong-ingress
  namespace: disperser-v2
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing  # ALB will be internet-facing
    alb.ingress.kubernetes.io/target-type: ip  # Target IPs (not instance ports)
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:goes:here
spec:
  ingressClassName: alb  # Specify ALB ingress class here
  rules:
  - http:
      paths:
      - path: /pingpong.PingService # ping
        pathType: Prefix
        backend:
          service:
            name: ping-service
            port:
              number: 50051
      - path: /pingpong.PongService # pong
        pathType: Prefix
        backend:
          service:
            name: pong-service
            port:
              number: 50052
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reflector-service
            port:
              number: 50057
