---
apiVersion: v1
kind: Pod
metadata:
  name: pong-pod
  namespace: disperser-v2
  labels:
    app: pong-app
spec:
  containers:
  - image: ghcr.io/pschork/pingpong/pong:latest
    imagePullPolicy: Always
    name: pong-container
    ports:
      - containerPort: 50052
      - containerPort: 50062
    livenessProbe:
      httpGet:
        path: /healthz  # Specify the path for health check
        port: 50062      # Use the healthPort defined above
      initialDelaySeconds: 1
      periodSeconds: 10
  restartPolicy: Always
  tolerations:
    - key: "disperser-v2"
      operator: "Equal"
      value: "1"
      effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: pong-service
  namespace: disperser-v2
spec:
  selector:
    app: pong-app
  ports:
  - protocol: TCP
    name: grpc
    port: 50052
    targetPort: 50052
  - protocol: TCP
    name: health
    port: 50062
    targetPort: 50062
  type: ClusterIP

